### ISSUE TITLE
[Umbrella] Apache Celeborn Graduation Tasks

### ISSUE THREAD

**Issue by FMX** [apache/celeborn#2415]
### Describe the proposal
The ASF board has approved a resolution to graduate Celeborn into a full Top Level Project. Thanks to everyone for your help to get to this point.

To transition from the Apache Incubator to a new TLP, there's a few action items we need to do to complete the transition. These are identified by https://incubator.apache.org/guides/transferring.html#life_after_graduation.

### Task list

- Update Incubator status records
  - [x] Update the incubator status file (in svn)
    https://svn.apache.org/repos/asf/incubator/public/trunk/content/projects/celeborn.xml
  - [x] Update podling status page
    https://incubator.apache.org/projects/
    https://incubator.apache.org/projects/celeborn.html
    https://svn.apache.org/repos/asf/incubator/public/trunk/content/podlings.xml
- Source repo changes
  - [x] Create JIRA ticket INFRA-25635 to request ASF Infra remove "incubator-" prefix of git repos
    https://github.com/apache/incubator-celeborn
    https://github.com/apache/incubator-celeborn-website
  - [x] Create JIRA ticket INFRA-25636 to request ASF Infra move dist folder in SVN repositories from the incubator to other locations
    old: https://dist.apache.org/repos/dist/release/incubator/celeborn
    new: https://dist.apache.org/repos/dist/release/celeborn
  - [x] Post announcement to dev list telling everyone the repo is about repos renaming
  - [x] Post an announcement containing instructions for developers describing how to change their git remotes
    https://lists.apache.org/thread/5yhb6z8g1bvy5kptkf7b8loy28my8hnc
  - [x] Update website, pom.xml, and other resources to point to the new repository location
 Post an announcement containing instructions for developers describing how to change their git remotes.

 Update website, pom.xml, and other resources to point to the new repository location
- Source code
  - [x] Remove "Incubating" from source code
  - [x] Remove DISCLAIMER from git repo
  - [x] Update Release scripts and template

- Websites
  - [x] Remove incubating/podling related resources from the website
  - [x] Update the process for becoming a committer or joining PMC
 
- Ecosystem
  - [x] Remove Incubating from third party projects including Gluten.
     - [x] Gluten: https://github.com/apache/incubator-gluten/issues/5142.
